puntos y espacio arreglados
Jacatove/parimpar pull request #1
Opened 2021-02-06 20:50 UTC by Jacatove

No debimos pasar este error

2021-02-06 21:07 UTC, javimate requested changes
También aplica la idea a la librería

2021-02-07 00:45 UTC, Jacatove commented
cambios hechos, por fa hazme el merge

2021-02-07 00:55 UTC, javimate approved these changes
por fin cabezón

2021-02-07 00:55 UTC, javimate commented on main.py
> +numero = input('Anita pide que ingrese un número para saber si es par o impar:')
@Jacatove  deshiciste lo que se había hecho, corrígelo

2021-02-07 00:56 UTC, merged